"""initial schema

Revision ID: a67826005c70
Revises: 
Create Date: 2026-06-11 16:05:27.267328
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a67826005c70'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'TRANSCRIBED', 'VIBE_SET', 'GENERATING', 'COMPLETE', name='project_status'), nullable=False),
    sa.Column('vibe_description', sa.Text(), nullable=True),
    sa.Column('vibe_keywords', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('language', sa.Enum('HI_DEV', 'HI_ROM', 'EN', name='language'), nullable=False),
    sa.Column('visual_mode', sa.Enum('STOCK', 'CUSTOM', name='visual_mode'), nullable=True),
    sa.Column('custom_video_url', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('original_url', sa.String(length=1024), nullable=False),
    sa.Column('trimmed_url', sa.String(length=1024), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('beat_timestamps', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('tempo_bpm', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clip_pool',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('pexels_clip_id', sa.String(length=255), nullable=False),
    sa.Column('clip_url', sa.String(length=1024), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lyrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('words', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_transcription', sa.Text(), nullable=True),
    sa.Column('last_edited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_reels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.Integer(), nullable=False),
    sa.Column('text_style', sa.Integer(), nullable=False),
    sa.Column('clip_pool_id', sa.UUID(), nullable=True),
    sa.Column('output_url', sa.String(length=1024), nullable=True),
    sa.Column('render_status', sa.Enum('QUEUED', 'RENDERING', 'COMPLETE', 'FAILED', name='render_status'), nullable=False),
    sa.Column('render_started_at', sa.DateTime(), nullable=True),
    sa.Column('render_completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['clip_pool_id'], ['clip_pool.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generated_reels')
    op.drop_table('lyrics')
    op.drop_table('clip_pool')
    op.drop_table('audio_files')
    op.drop_table('projects')
    # ### end Alembic commands ###
